### PR TITLE
Fix dll_path()

### PR DESCRIPTION
**Pull request by krlmlr**
so that needs_compile() and needs_clean() work properly again.

### CODE REVIEW

**Comment by mpadge** [comment]
I'm presumably having the same problem (`needs_compile()` **always** recompiles coz `dll_path` returns a double lot of `find_root` paths rather than the single `pkgname`, so `mtime(dll_path(path))` is always `NULL` and recompile is flagged), and this PR solves it, **BUT** the problem is not reproducible! On a fresh `lxc` install, `compile_dll()` works as expected and does not recompile. I'm still digging for an ultimate cause, so if i find anything further, I'll flag it here.

**Comment by mpadge** [comment]
Proximal cause: installing `pkgdown`. Reproducible with clean `lxc`. After `pkgdown` install, `pkgbuild::compile_dll()` prompts recompile every single time. Obviously related to the remote `devtools` install, but how?

**Comment by krlmlr** [comment]
Thanks. What is installed when you install `pkgdown` in lxc?

**Comment by mpadge** [comment]
Full list in clean install of `pkgdown` (with `devtools` pre-installed) is:
```
asserthat, rprojroot, backports, desc, evaluate, highlight, magick, DBI, lazyeval, tibble, 
dplyr, purrr, brew, commonmark, roxygen2, yaml, xml2, base64enc, bitops, caTools, 
htmltools, highr, markdown, knitr, rmarkdown, callr, pkgbuild, devtools.
```
but the problem almost certainly lies with updating to `dev` versions of `devtools/pkgbuild` (from `devtools 1.12.0` - the last integrated version - to current `1.12.0.9000` with separate `pkgload` and `pkgbuild`. Note that `dll_path()` in `1.12.0` used to be closer to your suggested PR:
```
dll_path <- function(pkg = ".") {
  pkg <- as.package(pkg)

  name <- paste(pkg$package, .Platform$dynlib.ext, sep = "")
  file.path(pkg$path, "src", name)
}
```
where obviously passing `pkg="."` and using `pkg$package` is a bit silly.

**Comment by lionel-** [comment]
This fixes intempestive recompilations for me, thanks.

**Comment by gaborcsardi** [comment]
👍 Looks good to me!

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
